### ISSUE TITLE
Add Blog Data

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/wsvvrijheid#109]
### Describe the feature you'd like to request

Draft data should be removed and real data should be added.

### Describe the solution you'd like

- [x] Remove draft data
- [x] Add real data in Strapi
- [ ] Check SEO

**Comment by MustafaTRKYLMZ** [comment]
I added real blog data in the strapi

**Comment by 7alip** [comment]
I will check the SEO, if it's necessary I may create a  PR for it. Otherwise we can close the issue after my approcal.
