### ISSUE TITLE
Activity Data

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/wsvvrijheid#112]
### Describe the feature you'd like to request

Draft data should be removed and if we have it real data should be added.

### Describe the solution you'd like

- [x] Remove draft data
- [x] Add real data in Strapi if we have orherwise add "No content" design
- [x] Check SEO

**Comment by MustafaTRKYLMZ** [comment]
How can we add youtube video in the activity page ?For example we have sort film which is empathy. We want to see it in the activity page.
