### ISSUE TITLE
Volunteers Data

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/wsvvrijheid#114]
### Describe the feature you'd like to request

Draft users should be removed and real users should be added.

### Describe the solution you'd like

- [x] Remove draft users
- [x] Add real data in Strapi

**Comment by MustafaTRKYLMZ** [comment]
I added real volunteers in strapi. If you like, we can close this issue @7alip 
By the way, I upladed project information with real information. We can close them but I didn't like the academy information. That's correct but we can improve a little bit. What do you think

**Comment by 7alip** [comment]
Looks good.  We can close this.

**Comment by MustafaTRKYLMZ** [comment]
Data added in the strapi
