### ISSUE TITLE
links

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/wsvvrijheid#131]
### Describe the bug

Projects links doesn't working, an also external link (samenvvv( desing should improve. We don't have to see link name which is www.samenvvv.nl. We can use iexternal con without text instead of text. Example : 
![image](https://user-images.githubusercontent.com/58182269/170935695-21b25659-b5b7-4085-80f3-e78492c14474.png)

 

### What did not work

Projects page links where are home page and header menu 

### Reproduce

Home page and header menu 

### What browsers are you seeing the problem on?

Chrome

**Comment by MustafaTRKYLMZ** [comment]
I added correct link in the strapi, When you checked, we can close it @7alip

**Comment by 7alip** [comment]
Yes, let's merge!

**Comment by MustafaTRKYLMZ** [comment]
fixed
