### ISSUE TITLE
Send mail when a new art is uploaded

### ISSUE THREAD

**Issue by 7alip** [wsvvrijheid/wsvvrijheid#150]
### Describe the feature you'd like to request

TODO

### Describe the solution you'd like

TODO

**Comment by MustafaTRKYLMZ** [comment]
It is working I recieve email when someone appled for become volunteer. 



{
  "id": 31,
  "username": "846453",
  "name": null,
  "email": "cana66331@gmail.com",
  "bio": null,
  "occupation": "",
  "phone": "+31684487099",
  "country": "NL",
  "availableHours": 1,
  "heardFrom": "other",
  "comment": "deneme ",
  "linkedin": null,
  "twitter": null,
  "instagram": null,
  "facebook": null,
  "inMailingList": false,
  "approved": false,
  "isPublic": true,
  "createdAt": "2022-06-08T09:33:57.101Z",
  "updatedAt": "2022-06-08T09:33:57.101Z",
  "publishedAt": "2022-06-08T09:33:57.039Z"
}

I noticed some bug which is name is null. But it is out of the topic for this branch. That is why I am closing this issue and I am opining new bug issue.

**Comment by MustafaTRKYLMZ** [comment]
email is working.

**Comment by MustafaTRKYLMZ** [comment]
email is working
