### ISSUE TITLE
Custom Donation amount

### ISSUE THREAD

**Issue by MustafaTRKYLMZ** [wsvvrijheid/wsvvrijheid#61]
### Describe the feature you'd like to request

You can write custom amount which is you want to donate

### Describe the solution you'd like

This input should be editable. You can type that how much money you want to donate

custom amount
Annual donate
Single donate

**Comment by 7alip** [comment]
We can set custom domain by swiping the slider. Do we need an extra input area there? I'm not sure if it's better in terms of UX @MustafaTRKYLMZ

**Comment by MustafaTRKYLMZ** [comment]
I think we need extra input. Because some people wants custom amount by themself. In my opinion.

**Comment by 7alip** [comment]
<img width="568" alt="Screenshot 2022-04-13 at 10 12 45" src="https://user-images.githubusercontent.com/22167684/163131139-4eb1e9fd-216c-45c2-bbba-115e29d7bef0.png">

I mean they can already set a custom amount up to €100. You would like to have a custom input field for those who may want to donate more than €100 then?

**Comment by MustafaTRKYLMZ** [comment]
![Screenshot_20220413-121440_Chrome](https://user-images.githubusercontent.com/58182269/163157104-ee2eceb4-1956-4aa6-a518-c4afe62ece05.jpg)
Gere is the example. When you chose some amount you can edit if you want. 
And also one time ore for example each month you can pay.

**Comment by 7alip** [comment]
Editing amount is also available in our example but it allows only up to €100. To clarify, we have two issues here.

- Custom input field
  - Remove the slider and show a custom input field instead
  - Or keep the slider and add extra custom input field
  - Allow unlimited amounts
- Subscription (A new issue might be created for this feature)

**Comment by MustafaTRKYLMZ** [comment]
Or hide slider and show input field once user clicks on the Custom button like in your example (I prefer this)

I agree with this. 
Do we need new issue instesnd of this.

**Comment by 7alip** [comment]
I assume this issue is only for input field. We can create another issue titled `Recurring Donation (Subscription)`
